[features]
seeds = false
skip-lint = false
[programs.localnet]
beacon_aid_relief = "BhENLVpEECmmibKWHiHKCxch3Q6FHTJ42faPASkLWSMS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alhajibarrie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
