// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://plcjtjchihvwcnxjtwdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsY2p0amNoaWh2d2NueGp0d2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NjIwMTcsImV4cCI6MjA1MjQzODAxN30.8viNv6koMji9FUKxHytO_P69GC-CcZ7w5WpC0Ik0PIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
	SUPABASE_URL,
	SUPABASE_PUBLISHABLE_KEY
);
