name: Deploy Solana Program

on:
 push:
  branches:
   - main # Change this if you want a different branch to trigger deployments

jobs:
 deploy:
  runs-on: ubuntu-20.04

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup Anchor framework
     uses: metadaoproject/setup-anchor@v1.2

   - name: Setup Solana CLI
     run: |
      sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
      solana --version

   - name: Configure Solana CLI
     run: |
      solana config set --url https://api.testnet.solana.com
      echo "${{ secrets.SOLANA_WALLET }}" > /home/runner/.config/solana/id.json
      chmod 600 /home/runner/.config/solana/id.json
      solana address

   - name: Build the Solana program
     run: anchor build

   - name: Deploy the program to Testnet
     run: anchor deploy --provider.cluster https://api.testnet.solana.com
