name: Deploy Solana Program

on:
 push:
  branches:
   - main # Change this if you want a different branch to trigger deployments

jobs:
 deploy:
  runs-on: ubuntu-20.04

  steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Setup Anchor framework
     uses: metaDAOproject/setup-anchor@v3.1

   - name: Configure Solana CLI
     run: |
      solana config set --url https://api.testnet.solana.com
      echo "${{ secrets.SOLANA_WALLET }}" > /home/runner/.config/solana/id.json
      chmod 600 /home/runner/.config/solana/id.json
      solana address

   - name: Build the Solana program
     run: anchor build

   - name: Deploy the program to Testnet
     run: anchor deploy --provider.cluster https://api.testnet.solana.com
